### PR TITLE
Renames limit -> max_limit.

### PR DESCRIPTION
**Pull request by marcovc**
Additionally renames member limit_with_fee() to max_limit_with_fee().
And also fixes some unit tests that were failing for an unrelated reason.

### CODE REVIEW

**Comment by marcovc** [comment]
I just realized "max_limit" is kind of a pleonasm. What do you think about "max_xrate" or "max_rate" instead?

**Comment by twalth3r** [comment]
> I just realized "max_limit" is kind of a pleonasm. What do you think about "max_xrate" or "max_rate" instead?

Adding "pleonasm" to the list of words I want to use more frequently in every-day conversation!

Hm, this naming is tough. Having a max_xrate and min_xrate doesn't really nail what they represent. It sounds a little bit different (better?) with "limit", but also not great. Could there be something with "lower" and "upper"?

**Comment by marcovc** [comment]
> Adding "pleonasm" to the list of words I want to use more frequently in every-day conversation!

Ahah. I guess these latin/greek words are more uncommon in Germanic languages.

> Having a max_xrate and min_xrate doesn't really nail what they represent.

Why do you feel that way? For me, like "max_sell_amount" states the maximum amount the trader is willing to sell, "max_xrate" states the maximum exchange rate the trader is willing to accept.

I'm also fine to keep it as it is for now!

**Review by twalth3r — APPROVED** [review]
Looks good!

**Pull request merged**
